### ISSUE TITLE
Questions for some hyperparameters

### ISSUE THREAD

**Issue by Chreer** [tsinghua-fib-lab/Large-Scale-MARL-GATMF#1]
I‘ve tried to implement the experiment in the **grid_world**, but I find the reward and the loss don't seem reasonable. So I checked the hyperparameters,  finding that the **gamma** in the figure is set to **0**. 
I don't understand why it is set to 0, and could you kindly offer the hyperparameters that you used in the experiment **grid_world**   
![image](https://github.com/tsinghua-fib-lab/Large-Scale-MARL-GATMF/assets/97589171/6e0a2183-9031-46c9-8cf9-b8d016070056)

**Comment by Chreer** [comment]
Hi, could you please help me with the problem above, expecting for the hyperparameters that you used in the experiment **grid_world**.

**Comment by haohaoqian** [comment]
It is 0 actually.
Because in this gird world toy-task, it seems that short-term focusing agent works the best.....
However, this can not be generalized to other scenarios, for example, gamma is set to be 0.6 in the real world scenarios.
I recommend that you can try the real-world experiment, which has more real-world meanings than the grid world toy data.
